name: Skyblock
version: '${project.version}'
main: com.sweattypalms.skyblock.SkyBlock
api-version: '1.17'
authors: [sweattypalms, devil_gamer_xd]
description: A Hypixel Skyblock remake plugin
website: sweattypalms.me
commands:
  test:
    description: Test command
    usage: /<command>
  gms:
    description: Sets gamemode to survival
    usage: /<command>
  gmc:
    description: Sets gamemode to creative
    usage: /<command>
  gmss:
    description: Sets gamemode to spectator
    usage: /<command>
